version: '3'

services:
  db:
    image: postgres
  dbadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "test@example.com"
      PGADMIN_DEFAULT_PASSWORD: "changeME2019"
    ports: 
    - "5450:80"
    depends_on:
      - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
