version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    volumes: 
      - data:/var/lib/postgresql/data 
    networks:
      - backend

  dbadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "test@example.com"
      PGADMIN_DEFAULT_PASSWORD: "changeME2019"
    ports: 
      - "5450:80"
    depends_on:
      - db
    networks:
      - backend
        
  web:
    build: .
    command: ["./wait-for-postgres.sh", "db", "python", "app.py"] #wait for it is temp, see https://docs.docker.com/compose/startup-order/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  data:
          
networks:
  backend:
    driver: bridge
