# Generated by Django 2.1.7 on 2019-06-29 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_migraines_mgstart_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='migraines',
            name='mgend_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
